[package]
name = "vebb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socket2 = "0.5"
http = "0.2"
bytes = "1.4"
ascii = "1.1"
